# Site settings
title: Code.PArents()
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Code Parents is for people with little or no prior computing experience, who would like to be better prepared to encourage and support children in starting to explore coding.
baseurl: "/code.parents" # the subpath of your site, e.g. /blog/
url: "http://bseymour.github.io" # the base hostname & protocol for your site
twitter_username: bseymour
github_username:  bseymour

# Build settings
markdown: kramdown
